/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desingclothing;

import baseDatos.conexionMYSQL;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import javax.swing.*;
import javax.swing.Icon;

/**
 *
 * @author jl-im
 */
public class cliente extends javax.swing.JFrame {

    static void addItem(String ns1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    DefaultTableModel modelo= new DefaultTableModel();

    /**
     * Creates new form cliente
     */
    public cliente() {
        initComponents();
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/imagenes/reg.png"));
        ImageIcon imagen2=new ImageIcon(getClass().getResource("/imagenes/act.png"));
        ImageIcon imagen3=new ImageIcon(getClass().getResource("/imagenes/bor.png"));
        ImageIcon imagen4=new ImageIcon(getClass().getResource("/imagenes/dev.png"));
        ImageIcon imagen5=new ImageIcon(getClass().getResource("/imagenes/logo.png"));
        ImageIcon imagen6=new ImageIcon(getClass().getResource("/imagenes/most.png"));
        Icon fon1=new ImageIcon(imagen6.getImage().getScaledInstance(a1.getWidth(),a1.getHeight(),Image.SCALE_DEFAULT));
        Icon fon2=new ImageIcon(imagen1.getImage().getScaledInstance(reg.getWidth(),reg.getHeight(),Image.SCALE_DEFAULT));
        Icon fon3=new ImageIcon(imagen2.getImage().getScaledInstance(a2.getWidth(),a2.getHeight(),Image.SCALE_DEFAULT));
        Icon fon4=new ImageIcon(imagen3.getImage().getScaledInstance(borrar.getWidth(),borrar.getHeight(),Image.SCALE_DEFAULT));
        Icon fon5=new ImageIcon(imagen4.getImage().getScaledInstance(regresar.getWidth(),regresar.getHeight(),Image.SCALE_DEFAULT));
        Icon fon6=new ImageIcon(imagen5.getImage().getScaledInstance(logo.getWidth(),logo.getHeight(),Image.SCALE_DEFAULT));
        a1.setIcon(fon1);
        reg.setIcon(fon2);
        a2.setIcon(fon3);
        borrar.setIcon(fon4); 
        regresar.setIcon(fon5); 
        logo.setIcon(fon6);
        this.repaint();
        this.setSize(new Dimension(700,510)); 
        setLocationRelativeTo(null);
        c.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        n = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ce = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        borrar = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        a1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        h = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("APELLIDOS");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("DIRECCION");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("TELEFONO");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("NOMBRES");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("COD");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("CEDULA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        borrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel4.add(borrar);
        borrar.setBounds(210, 20, 70, 40);

        a2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel4.add(a2);
        a2.setBounds(120, 20, 70, 40);

        regresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel4.add(regresar);
        regresar.setBounds(300, 20, 70, 40);

        reg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jPanel4.add(reg);
        reg.setBounds(30, 20, 70, 40);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel8.setText("ACTUALIZAR");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(120, 0, 81, 17);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel10.setText("REGRESAR");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(290, 0, 69, 17);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel9.setText("BORRAR");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(220, 0, 54, 17);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setText("REGISTRAR");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 0, 73, 17);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        a1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel5.add(a1);
        a1.setBounds(10, 0, 70, 60);

        result.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "cedula", "nombres", "apellidos", "direccion", "telefono"
            }
        ));
        result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(result);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 70, 596, 409);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("REGISTRO DE CLIENTES");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 30, 270, 40);
        getContentPane().add(logo);
        logo.setBounds(0, 0, 100, 70);

        h.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(h);
        h.setBounds(10, 290, 11, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
    conexionMYSQL mysql=new conexionMYSQL();
        Connection cn=mysql.Conectar();
	PreparedStatement ps=null;
	try {
		String query="delete from cliente where ID_nit=?";
		ps=cn.prepareStatement(query);
		ps.setString(1, h.getText());
		ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO");
                mostrar();
	} 
        catch (SQLException ex) 
         {
           JOptionPane.showMessageDialog(null, ex.getMessage());
          } 
    }//GEN-LAST:event_borrarActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
                                         
    conexionMYSQL mysql=new conexionMYSQL();
    Connection cn=mysql.Conectar();
    String sSQL = "";
    String cedu,nn,ap,di,te;
    cedu=ce.getText();
    nn=n.getText();
    ap=a.getText();
    di=d.getText();
    te=t.getText();

     sSQL = "UPDATE registro SET cedula=?,nombres=?,apellidos=?,direccion=?,telefono=?";
String mensaje = "Los datos se han Modificado de Manera Satisfactoria...";

try
{
PreparedStatement pst = cn.prepareStatement(sSQL);
     pst.setString(1,cedu);
     pst.setString(2,nn);
     pst.setString(3,ap);
     pst.setString(4,di);
     pst.setString(5,te);
int n = pst.executeUpdate();

if(n > 0)
{
            JOptionPane.showMessageDialog(null, mensaje);
           mostrar();
}
}
            catch (SQLException ex)
    {
             JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_a2ActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        ventas e2=new ventas();
        e2.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        
    conexionMYSQL mysql=new conexionMYSQL();
    Connection cn=mysql.Conectar();
    String Ssql="";
    String mensaje="";
    String cedu,nn,ap,di,te;
    cedu=ce.getText();
    nn=n.getText();
    ap=a.getText();
    di=d.getText();
    te=t.getText();
    Ssql="INSERT INTO cliente(cedula,nombres,apellidos,direccion,telefono) VALUES(?,?,?,?,?)";
    mensaje="los datos se ingresado correctamente";
    try{
     PreparedStatement pst= cn.prepareStatement(Ssql); 
     pst.setString(1,cedu);
     pst.setString(2,nn);
     pst.setString(3,ap);
     pst.setString(4,di);
     pst.setString(5,te);
     
     int n= pst.executeUpdate();
     if(n>0){
         JOptionPane.showMessageDialog(null, mensaje);
         mostrar();
     }
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,ex);
    }
    }//GEN-LAST:event_regActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
    conexionMYSQL mysql=new conexionMYSQL();
        Connection cn=mysql.Conectar();
	PreparedStatement ps=null;
	ResultSet rs=null;
        try {
		String query="select * from cliente";
		ps=cn.prepareStatement(query);
		rs=ps.executeQuery();
                modelo.setRowCount(0);
                modelo.setColumnIdentifiers(new Object[]{"ID_nit","cedula","nombres","apellidos","direccion","telefono"});
                            
              while(rs.next())
              {
                 modelo.addRow(new Object[]{rs.getString("ID_nit"),rs.getString("cedula"),rs.getString("nombres"),rs.getString("apellidos"),rs.getString("direccion"),rs.getString("telefono")}); 
              }
              
               result.setModel(modelo);
 
	}  
        catch (SQLException ex) 
        {
         JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_a1ActionPerformed

    private void resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultMouseClicked
    int fila= result.getSelectedRow();
         
       if (fila<0)
       {
             JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
       }
       else
       {
           String id=result.getValueAt(fila,0).toString();
           String cedula=result.getValueAt(fila,1).toString();
           String nombre=result.getValueAt(fila,2).toString();
           String apellido=result.getValueAt(fila,3).toString();
           String direccion=result.getValueAt(fila,4).toString();
           String telefono=result.getValueAt(fila,5).toString();

           c.setText(id);
           ce.setText(cedula);
           n.setText(nombre);
           a.setText(apellido);
           d.setText(direccion);
           t.setText(telefono);
           
       }  
    }//GEN-LAST:event_resultMouseClicked
 private void mostrar()
  {
        conexionMYSQL mysql=new conexionMYSQL();
        Connection cn=mysql.Conectar();
	PreparedStatement ps=null;
	ResultSet rs=null;
        try {
		String query="select * from cliente";
		ps=cn.prepareStatement(query);
		rs=ps.executeQuery();
                modelo.setRowCount(0);
                modelo.setColumnIdentifiers(new Object[]{"ID_nit","cedula","nombres","apellidos","direccion","telefono"});
                            
              while(rs.next())
              {
                 modelo.addRow(new Object[]{rs.getString("ID_nit"),rs.getString("cedula"),rs.getString("nombres"),rs.getString("apellidos"),rs.getString("direccion"),rs.getString("telefono")}); 
              }
              
               result.setModel(modelo);
 
	}  
        catch (SQLException ex) 
        {
         JOptionPane.showMessageDialog(null, ex.getMessage());
        }} 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField c;
    private javax.swing.JTextField ce;
    private javax.swing.JTextField d;
    private javax.swing.JLabel h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField n;
    private javax.swing.JButton reg;
    private javax.swing.JButton regresar;
    private javax.swing.JTable result;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
