/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desingclothing;

import baseDatos.conexionMYSQL;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import javax.swing.*;
import javax.swing.Icon;

/**
 *
 * @author jl-im
 */
public class productos extends javax.swing.JFrame {
DefaultTableModel modelo= new DefaultTableModel();
    /**
     * Creates new form productos
     */
    public productos() {
        initComponents();
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/imagenes/reg.png"));
        ImageIcon imagen2=new ImageIcon(getClass().getResource("/imagenes/act.png"));
        ImageIcon imagen3=new ImageIcon(getClass().getResource("/imagenes/bor.png"));
        ImageIcon imagen4=new ImageIcon(getClass().getResource("/imagenes/dev.png"));
        ImageIcon imagen5=new ImageIcon(getClass().getResource("/imagenes/logo.png"));
        ImageIcon imagen6=new ImageIcon(getClass().getResource("/imagenes/most.png"));
        Icon fon1=new ImageIcon(imagen6.getImage().getScaledInstance(a1.getWidth(),a1.getHeight(),Image.SCALE_DEFAULT));
        Icon fon2=new ImageIcon(imagen1.getImage().getScaledInstance(a5.getWidth(),a5.getHeight(),Image.SCALE_DEFAULT));
        Icon fon3=new ImageIcon(imagen2.getImage().getScaledInstance(a2.getWidth(),a2.getHeight(),Image.SCALE_DEFAULT));
        Icon fon4=new ImageIcon(imagen3.getImage().getScaledInstance(a3.getWidth(),a3.getHeight(),Image.SCALE_DEFAULT));
        Icon fon5=new ImageIcon(imagen4.getImage().getScaledInstance(a4.getWidth(),a4.getHeight(),Image.SCALE_DEFAULT));
        Icon fon6=new ImageIcon(imagen5.getImage().getScaledInstance(logo.getWidth(),logo.getHeight(),Image.SCALE_DEFAULT));
        a1.setIcon(fon1);
        a5.setIcon(fon2);
        a2.setIcon(fon3);
        a3.setIcon(fon4); 
        a4.setIcon(fon5); 
        logo.setIcon(fon6);
        this.repaint();
        this.setSize(new Dimension(750,510)); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nproductos = new javax.swing.JTextField();
        cproducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        a1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        h = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nombre producto");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 14, 109, 17);
        jPanel1.add(nproductos);
        nproductos.setBounds(131, 13, 134, 30);
        jPanel1.add(cproducto);
        cproducto.setBounds(385, 13, 158, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Cod producto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(283, 14, 86, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Precio");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 52, 40, 17);
        jPanel1.add(p);
        p.setBounds(131, 51, 134, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Color");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(283, 52, 34, 17);
        jPanel1.add(c);
        c.setBounds(385, 51, 158, 30);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        a2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel4.add(a2);
        a2.setBounds(100, 20, 70, 40);

        a3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel4.add(a3);
        a3.setBounds(180, 20, 70, 40);

        a4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel4.add(a4);
        a4.setBounds(260, 20, 70, 40);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setText("REGISTRAR");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 0, 73, 17);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel8.setText("ACTUALIZAR");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(100, 0, 81, 17);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel9.setText("BORRAR");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(190, 0, 54, 17);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel10.setText("REGRESAR");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(260, 0, 69, 17);

        a5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        jPanel4.add(a5);
        a5.setBounds(20, 20, 70, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(140, 100, 350, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        a1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel2.add(a1);
        a1.setBounds(10, 0, 70, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 240, 90, 70);

        result.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod producto", "Producto", "Precio", "Color"
            }
        ));
        result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(result);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 230, 480, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 50, 610, 380);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("PRODUCTOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 10, 140, 40);
        getContentPane().add(logo);
        logo.setBounds(0, 0, 90, 80);

        h.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(h);
        h.setBounds(30, 410, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
    conexionMYSQL mysql=new conexionMYSQL();
        Connection cn=mysql.Conectar();
	PreparedStatement ps=null;
	ResultSet rs=null;
        try {
		String query="select * from productos";
		ps=cn.prepareStatement(query);
		rs=ps.executeQuery();
                modelo.setRowCount(0);
                modelo.setColumnIdentifiers(new Object[]{"cod_nit", "cod_produtos","nombre_producto","precio", "color"});
                            
              while(rs.next())
              {
                 modelo.addRow(new Object[]{rs.getString("cod_nit"),rs.getString("cod_produtos"),rs.getString("nombre_producto"),rs.getString("precio"),rs.getString("color")}); 
              }
              
               result.setModel(modelo);
 
	}  
        catch (SQLException ex) 
        {
         JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
  conexionMYSQL mysql=new conexionMYSQL();
    Connection cn=mysql.Conectar();
    String sSQL = "";
   String nprod,cprod,pre,col;
    nprod=nproductos.getText();
    cprod=cproducto.getText();
    pre=p.getText();
    col=c.getText();

     sSQL = "UPDATE productos SET cod_produtos=?,nombre_producto=?,precio=?,color=? WHERE cod_nit";
String mensaje = "Los datos se han Modificado de Manera Satisfactoria...";

try
{
PreparedStatement pst = cn.prepareStatement(sSQL);
     pst.setString(1,nprod);
     pst.setString(2,cprod);
     pst.setString(3,pre);
     pst.setString(4,col);
int n = pst.executeUpdate();

if(n > 0)
{
            JOptionPane.showMessageDialog(null, mensaje);
           mostrar();
}
}
            catch (SQLException ex)
    {
             JOptionPane.showMessageDialog(null, ex);
}     
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
    conexionMYSQL mysql=new conexionMYSQL();
        Connection cn=mysql.Conectar();
	PreparedStatement ps=null;
	try {
		String query="delete from registro where cod_nit=?";
		ps=cn.prepareStatement(query);
		ps.setString(1, h.getText());
		ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO");
                mostrar();
	} 
        catch (SQLException ex) 
         {
           JOptionPane.showMessageDialog(null, ex.getMessage());
          }
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        menu_vendedor e2=new menu_vendedor();
        e2.setVisible(true);
        dispose();
    }//GEN-LAST:event_a4ActionPerformed

    private void resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultMouseClicked
  int fila= result.getSelectedRow();
         
       if (fila<0)
       {
             JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
       }
       else
       {
           String id=result.getValueAt(fila,0).toString();
           String n1productos=result.getValueAt(fila,1).toString();
           String c1productos=result.getValueAt(fila,2).toString();
           String precio=result.getValueAt(fila,1).toString();
           String color=result.getValueAt(fila,2).toString();

           nproductos.setText(n1productos);
           cproducto.setText(c1productos);
           p.setText(precio);
           c.setText(color);
           h.setText(id);
           
       }  
    }//GEN-LAST:event_resultMouseClicked

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
       conexionMYSQL mysql=new conexionMYSQL();
    Connection cn=mysql.Conectar();
    String Ssql="";
    String mensaje="";
    String nprod,cprod,pre,col;
    nprod=nproductos.getText();
    cprod=cproducto.getText();
    pre=p.getText();
    col=c.getText();
    Ssql="INSERT INTO productos(cod_produtos,nombre_producto,precio,color) VALUES(?,?,?,?)";
    mensaje="los datos se ingresado correctamente";
    
    
    try{
     PreparedStatement pst= cn.prepareStatement(Ssql); 
     pst.setString(1,nprod);
     pst.setString(2,cprod);
     pst.setString(3,pre);
     pst.setString(4,col);
     
     int n= pst.executeUpdate();
     if(n>0){
         JOptionPane.showMessageDialog(null, mensaje);
         mostrar();
     }
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,ex);
    }
    }//GEN-LAST:event_a5ActionPerformed

     private void mostrar()
  {
        conexionMYSQL mysql=new conexionMYSQL();
        Connection cn=mysql.Conectar();
	PreparedStatement ps=null;
	ResultSet rs=null;
        try {
		String query="select * from productos";
		ps=cn.prepareStatement(query);
		rs=ps.executeQuery();
                modelo.setRowCount(0);
                modelo.setColumnIdentifiers(new Object[]{"cod_nit", "cod_produtos","nombre_producto","precio", "color"});
                            
              while(rs.next())
              {
                 modelo.addRow(new Object[]{rs.getString("cod_nit"),rs.getString("cod_produtos"),rs.getString("nombre_producto"),rs.getString("precio"),rs.getString("color")}); 
              }
              
               result.setModel(modelo);
 
	}  
        catch (SQLException ex) 
        {
         JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
  }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton a5;
    private javax.swing.JTextField c;
    private javax.swing.JTextField cproducto;
    private javax.swing.JLabel h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nproductos;
    private javax.swing.JTextField p;
    private javax.swing.JTable result;
    // End of variables declaration//GEN-END:variables
}
